CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) UNIQUE NOT NULL,
  "email" varchar(35) UNIQUE NOT NULL,
  "password" varchar(30) UNIQUE NOT NULL,
  "age" int UNIQUE NOT NULL,
  "id_roles" int NOT NULL
);

CREATE TABLE "course_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "url" varchar(60) UNIQUE NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) UNIQUE NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) UNIQUE NOT NULL
);

CREATE TABLE "level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) UNIQUE NOT NULL
);

CREATE TABLE "teacher" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) UNIQUE NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "description" varchar(100) NOT NULL,
  "id_level" int NOT NULL,
  "id_teacher" int NOT NULL,
  "id_user" int NOT NULL,
  "id_course_video" int NOT NULL,
  "id_categories" int NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("id_roles") REFERENCES "roles" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("id_level") REFERENCES "level" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("id_teacher") REFERENCES "teacher" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("id_course_video") REFERENCES "course_videos" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("id_categories") REFERENCES "categories" ("id");




COMANDO DE CONSULTAS

courses=# SELECT * FROM courses;
 id |     title      |                    description                     | id_level | id_teacher | id_user | id_course_video | id_categories
----+----------------+----------------------------------------------------+----------+------------+---------+-----------------+---------------
  1 | Matematica     | Es un curso basico de la curricula de programacion |        1 |          1 |       1 |               1 |             1
  2 | Programacion I | Introducion a la programacion                      |        1 |          2 |       2 |               2 |             3
  3 | Literatura     | Aspectos en la vida cotidiana                      |        2 |          3 |       1 |               3 |             2
(3 filas)


courses=# SELECT * FROM users  WHERE name='Harvey Lopez';
 id |     name     |        email         | password  | age | id_roles
----+--------------+----------------------+-----------+-----+----------
  1 | Harvey Lopez | lopezharve@gmail.com | 123456789 |  40 |        3
(1 fila)

courses=# SELECT * FROM courses WHERE title='Matematica';
 id |   title    |                    description                     | id_level | id_teacher | id_user | id_course_video | id_categories
----+------------+----------------------------------------------------+----------+------------+---------+-----------------+---------------
  1 | Matematica | Es un curso basico de la curricula de programacion |        1 |          1 |       1 |               1 |             1
(1 fila)
