CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) UNIQUE NOT NULL,
  "email" varchar(35) UNIQUE NOT NULL,
  "password" varchar(30) UNIQUE NOT NULL,
  "age" int UNIQUE NOT NULL,
  "id_roles" int NOT NULL
);

CREATE TABLE "course_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "url" varchar(60) UNIQUE NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) UNIQUE NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) UNIQUE NOT NULL
);

CREATE TABLE "level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) UNIQUE NOT NULL
);

CREATE TABLE "teacher" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) UNIQUE NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "description" varchar(100) NOT NULL,
  "id_level" int NOT NULL,
  "id_teacher" int NOT NULL,
  "id_user" int NOT NULL,
  "id_course_video" int NOT NULL,
  "id_categories" int NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("id_roles") REFERENCES "roles" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("id_level") REFERENCES "level" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("id_teacher") REFERENCES "teacher" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("id_course_video") REFERENCES "course_videos" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("id_categories") REFERENCES "categories" ("id");


CREATE DATABASE courses:

INSERT INTO level (name) VALUES ('Principiante'), ('Medio'),('Avanzado');
INSERT INTO course_videos (title,url) VALUES ('Matematica','www.matematica.com.pe'),('Programacion I','www.programacion.com.pe'),('Literartura','www.literatura.com.pe');
INSERT INTO categories (name) VALUES ('Presencial'),('Semi presencial'),('Onlinea');
INSERT INTO roles (name) VALUES ('Admin'),('Teacher'),('Studen'); 
INSERT INTO teacher (name) VALUES ('Juan Ramon'),('Raul Gomez'),('Luis Marcelo');
INSERT INTO users (name,email,password,age,id_roles) VALUES ('Harvey Lopez','harvey@hotmail.com','123456789',35,3), ('Luis Felipe','felip@hotmail.com','123456789',45,3), ('Juan Ramon','harvey@hotmail.com','123456789',45,2);
INSERT INTO courses (title,description,id_level,id_teacher,id_users,id_course_videos,id_categories) VALUES ('Matematica','Curso basico etc...',1,1,1,1,1),('MaProgramacion I','Curso intermedio etc...',2,2,1,2,2),('Literatura','Curso avanzado etc...',3,3,2,3,3);



COMANDO DE CONSULTAS

courses=# SELECT * FROM courses;
 id |     title      |                    description                     | id_level | id_teacher | id_user | id_course_video | id_categories
----+----------------+----------------------------------------------------+----------+------------+---------+-----------------+---------------
  1 | Matematica     | Es un curso basico de la curricula de programacion |        1 |          1 |       1 |               1 |             1
  2 | Programacion I | Introducion a la programacion                      |        1 |          2 |       2 |               2 |             3
  3 | Literatura     | Aspectos en la vida cotidiana                      |        2 |          3 |       1 |               3 |             2
(3 filas)


courses=# SELECT * FROM users  WHERE name='Harvey Lopez';
 id |     name     |        email         | password  | age | id_roles
----+--------------+----------------------+-----------+-----+----------
  1 | Harvey Lopez | lopezharve@gmail.com | 123456789 |  40 |        3
(1 fila)

courses=# SELECT * FROM courses WHERE title='Matematica';
 id |   title    |                    description                     | id_level | id_teacher | id_user | id_course_video | id_categories
----+------------+----------------------------------------------------+----------+------------+---------+-----------------+---------------
  1 | Matematica | Es un curso basico de la curricula de programacion |        1 |          1 |       1 |               1 |             1
(1 fila)






USO DE JOIN

courses=# SELECT * FROM users JOIN roles ON roles.id = users.id_roles;
 id |      name      |        email         | password  | age | id_roles | id |  name
----+----------------+----------------------+-----------+-----+----------+----+---------
  1 | Harvey Lopez   | lopezharve@gmail.com | 123456789 |  40 |        3 |  3 | Studen
  2 | Nilton Baldeon | badeon@gmail.com     | 987654321 |  30 |        3 |  3 | Studen
  3 | Juan Ramon     | juanramon@gmail.com  | 22222221  |  38 |        2 |  2 | Teacher
(3 filas)


courses=# SELECT * FROM courses JOIN users ON users.id = courses.id_user;
 id |     title      |                    description                     | id_level | id_teacher | id_user | id_course_video | id_categories | id |      name      |        email         | password  | age | id_roles
----+----------------+----------------------------------------------------+----------+------------+---------+-----------------+---------------+----+----------------+----------------------+-----------+-----+----------
  1 | Matematica     | Es un curso basico de la curricula de programacion |        1 |          1 |       1 |               1 |             1 |  1 | Harvey Lopez   | lopezharve@gmail.com | 123456789 |  40 |        3
  2 | Programacion I | Introducion a la programacion                      |        1 |          2 |       2 |               2 |             3 |  2 | Nilton Baldeon | badeon@gmail.com     | 987654321 |  30 |        3
  3 | Literatura     | Aspectos en la vida cotidiana                      |        2 |          3 |       1 |               3 |             2 |  1 | Harvey Lopez   | lopezharve@gmail.com | 123456789 |  40 |        3
(3 filas)


courses=# SELECT courses.id, courses.title, users.name FROM courses JOIN users ON users.id = courses.id_user;
 id |     title      |      name
----+----------------+----------------
  1 | Matematica     | Harvey Lopez
  2 | Programacion I | Nilton Baldeon
  3 | Literatura     | Harvey Lopez
(3 filas)


courses=# SELECT courses.id, courses.title, users.name FROM courses JOIN users ON users.id = courses.id_user WHERE users.name='Harvey Lopez';
 id |   title    |     name
----+------------+--------------
  1 | Matematica | Harvey Lopez
  3 | Literatura | Harvey Lopez
(2 filas)


courses=# SELECT courses.id, courses.title, users.name, teacher.name,level.name FROM courses JOIN users ON users.id = courses.id_user JOIN teacher ON courses.id=teacher.id JOIN level ON courses.id=level.id;
 id |     title      |      name      |      name       |     name
----+----------------+----------------+-----------------+--------------
  1 | Matematica     | Harvey Lopez   | Juan Ramon      | Principiante
  2 | Programacion I | Nilton Baldeon | Ricardo Mallqui | Medio
  3 | Literatura     | Harvey Lopez   | Jose Carranza   | Avanzado
(3 filas)
         
courses=# SELECT courses.id, courses.title, users.name, teacher.name,level.name,course_videos.title FROM courses JOIN users ON users.id = courses.id_user JOIN teacher ON courses.id=teacher.id JOIN level ON courses.id=level.id JOIN course_videos ON courses.id=course_videos.id;
 id |     title      |      name      |      name       |     name     |     title
----+----------------+----------------+-----------------+--------------+----------------
  1 | Matematica     | Harvey Lopez   | Juan Ramon      | Principiante | Matematica
  2 | Programacion I | Nilton Baldeon | Ricardo Mallqui | Medio        | Programacion I
  3 | Literatura     | Harvey Lopez   | Jose Carranza   | Avanzado     | Literatura
(3 filas)